services:
  waha:
    image: devlikeapro/waha
    container_name: posat-waha
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./sessions:/app/.sessionss